### ISSUE TITLE
[OPINION NEEDED] Structure of test report

### ISSUE THREAD

**Issue by lorenzonodari** [Koldar/crashc#30]
I am implementing the TestReport structure and would like to receive an opinion regarding how to store the needed informations.

At the moment i am creating a structure which contains:
-generic test informations: the name of the parent testcase, the file which contains the test, etc...
-a list of snapshots of the sections crossed during the test
-the time of execution of the test

The last thing that i need to add is the exit status of the test. Thinking about it, i came to the conclusion that the exit status of the test should depend on the status of the last section executed.
i.e: if the last section was executed successfully, the test is considered to be passed, whereas it is considered failed when the status of the last section is "signal received" or "assertion failed", etc...

Firstly, do you think this approach could be correct? Or does it have some downside/pitfall that i'm not seeing?

Let me know what do you think about it!
Thanks

**Comment by Koldar** [comment]
First of all:
is your TestReport containing the runtime outcome of entire single TESTCASE inner loop? Or a single Depth inside the section tree. Just to make myself clear; given the section tree:
```
TESTCASE {
    WHEN1 {
        THEN1{}
        THEN2{}
    }
    WHEN2{
         THEN3{}
    }
    THEN4{}
}
```
**Your TestReport wants to represent a single TESTCASE inner loop** (thus `TESTCASE->WHEN1->THEN1->THEN2->THEN4`) **or a single path inside the section tree**(thus `TESTCASE->WHEN1->THEN1`)?

I think a test report should reflect a single TESTCASE inner loop because basically a CrashC TESTCASE it's just a compressed representation of several standard testcases. If so, you don't need a list of snapshots (as we thought about last time we had a meeting), but something more complex (in the example we need a tree).

We need to think about what the TestReport actually is: **it's a astructure associated to a CONTAINABLESECTION or it's associated with a single ASSERT**? What do you think? Depending on this last question, I can verify whether or not the data structure `TestReport` you've suggested is enough or not.

**Comment by lorenzonodari** [comment]
At the moment i am considering a TestReport to be associated, as you said, to a single TESTCASE inner loop but it is not clear to me why you think a list of snapshots would not be enough!

That said, i don't think a TestReport should be associate to a particular ASSERT nor to a single CONTAINABLESECTION. I just see it as a self-defined entity dependant on the flow of execution of the program, not on the data structures involved, but maybe i'm over-abstracting.

**Comment by Koldar** [comment]
Allow me to be clearer. Analyze the section tree in my previous comment; the section tree is:

```
TESTCASE
  - WHEN1
      - THEN1
      - THEN2
  - WHEN2
      - THEN3
  - THEN4
```

such test case involves 2 loops:

- `TESTCASE -> WHEN1 -> THEN1 -> THEN2 -> THEN4`
- `TESTCASE-> WHEN2 -> THEN3 -> THEN4`

As you can see in the first loop (but this happens in the second loop as well) you don't have that every section are in a single path of the section tree. Infact `THEN4` is **not** inside `WHEN1`. So a list is not enough: if you queried the list to fetch the parent of the snapshot `THEN4` it would return you `THEN2`, but it's actually snapshot `TESTCASE` (I assume the parent of snapshot is the element before the list, am i right?). With the tree you wouldn't have this problem at all.
