### ISSUE TITLE
Code style proposal

### ISSUE THREAD

**Issue by lorenzonodari** [Koldar/crashc#62]
I noticed that in the Linux kernel structure types are referenced by their struct tag, and not through a typedef.
This might help code comprehension by making clear which data types are structures and which are not.
How about we adopt this code style ourselves? I started quite liking that convention, what do you think about it?

**Comment by Koldar** [comment]
Prior to give you my opinion, I need to document myself. Stay tuned!

**Comment by Koldar** [comment]
Ok, my comment will be based upon the following 3 resources:

- https://stackoverflow.com/questions/252780/why-should-we-typedef-a-struct-so-often-in-c;
- http://yarchive.net/comp/linux/typedefs.html;
- https://www.kernel.org/doc/html/latest/process/coding-style.html#typedefs;

What I ended up understanding is that it's mainly a matter of taste. To clarify, there are 2 cateegories of developers which explicitly use "struct" instead of the typedefs:

1. some maintainers;
2. Kernel developers;

From what I discovered, the main downsides of using `typedef struct {...} struct_name` are the following:

1. This is the point of Linus: Given a variable, the typedef hides the fact that the variable is a structure. The structure may be a complex objects, so passing by value fills the stack in a non-trivial way; since the stack is generally small, allocating structure on the stack may end up in a stack smashing scenario [the last part is an addendum of mine]; by explicitly been forced to write "struct" before a variable the developer can be safely been warned by the syntax that such variable may take some amount of space in the stack;
2. may avoid some header inclusion: suppose you have "typedef struct bar{} Bar" in an header file called "bar.h". Supose you have "typedef struct foo{ declare a field of type bar here}". You have used only a typedef for bar, you are required to include in foo `bar.h` as well. In the second scenario, this is not necessary; This may end up avoiding circual header inclusions;
3. `printf`-like functons: having something like `typedef int counter_t` **hides** what is the correct format to put in a `printf`: which format should I use? `printf("%d", c);`, `printf("%lu", c);`, `printf("%u", c);`?

However, there are plenty of counter-example, so this code style is not always applied.

Ok, now my opinion: I agree with Linus, typedef **hides** the complexity of a variable. such hiding can indeed be harmful when coding in the kernel because Linux is designed to work even on devices with small stack size. The other 2 reasons are not so compelling instead.
Now, let's talk about crashC: does it have to be run inside small devices such that wrongly declare stuff on the stack might be run crashing? I don't think so: tests will probable be run on PCs with lots of stack space. Furthermore, crashC structs are almost all opaque, so you can't allocate them on the stack anyway.

I don't think we **need** such code style, so it's just a matter of preferences. However, it's indeed attractive to write code with such code style. What do you say? I have mixed feelings :)

**Comment by lorenzonodari** [comment]
I agree, we don't **need** this code style, i quite like the way it looks but I do also think that changing it right now would requite a bit of extra work on refactoring the code, which is a pretty boring task. Since most of our structs are opaque maybe it is better to keep our current style!
We can though keep this style in mind for future projects!

**Comment by Koldar** [comment]
You know, maybe we can use this code style just to train ourselves to use it. CrashC may be the best project to do so. I think we should refactor crashC code in order to use such style: we both find it attractive, so why not?

**Comment by lorenzonodari** [comment]
Let's adopt it then, no problem to me!
